@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Nov 30 23:10:34 +0900 2021
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_4bit_behav -key {Behavioral:sim_1:Functional:tb_4bit} -tclbatch tb_4bit.tcl -view D:/VIVADO_PROJECT/project_HW3_20160394/tb_4bit_behav.wcfg -log simulate.log"
call xsim  tb_4bit_behav -key {Behavioral:sim_1:Functional:tb_4bit} -tclbatch tb_4bit.tcl -view D:/VIVADO_PROJECT/project_HW3_20160394/tb_4bit_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
